INSERT INTO public."User"(email, name, role, "createdAt", "updatedAt")
VALUES (
        'hieupvph12651@fpt.edu.vn',
        'hieupvph12651',
        'admin',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'khiemmdph11447@fpt.edu.vn',
        'khiemmdph11447',
        'admin',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'duclqph11414@fpt.edu.vn',
        'duclqph11414',
        'admin',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'huyhtph07087@fpt.edu.vn',
        'huyhtph07087',
        'admin',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'tienbmph05304@fpt.edu.vn',
        'tienbmph05304',
        'admin',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'doanltph07885@fpt.edu.vn',
        'doanltph07885',
        'admin',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );